SixManagerSw/urls.py
from django.contrib import admin
from django.urls import path, include
#Las Ultimas dos librerías se ingresan, para que se puedan cargar imagenes en el administrador de django
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #Carga los templates
    path('', include('app.urls')),
    #Es util para crear el login, utilizando las herramientas de django
    path('accounts/',include('django.contrib.auth.urls')),
]

#Solo se utiliza en fase de desarrollo y no en producción
#Sirve para linkear la carpeta fisica con el settings de django
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path, include
from .views import eliminar_cliente, index, adm_clientes, adm_usuarios, listar_clientes, loginopcion, adm_ventas, listar_ventas, modificar_clientes,modificar_venta, eliminar_venta,export_clientes_xls,export_nota_venta_xls,  registro, reporte
urlpatterns = [
    
    path('jet/', include('jet.urls','jet')),
    path('index/', index , name="index"),
    path('adm_clientes/', adm_clientes, name="adm_clientes"),
    path('adm_usuarios/', adm_usuarios, name="adm_usuarios"),
    path('', loginopcion, name="loginopcion"),
    path('adm_venta/',adm_ventas, name="adm_ventas"),
    path('listar_clientes/',listar_clientes, name="listar_clientes"),
    path('listar_ventas/',listar_ventas, name="listar_ventas"),
    path('modificar_venta/<id>/',modificar_venta,name="modificar_venta"),
    path('eliminar_venta/<id>',eliminar_venta,name='eliminar_venta'),
    path('modificar_clientes/<id>',modificar_clientes,name="modificar_clientes"),
    path('eliminar_cliente/<id>',eliminar_cliente,name="eliminar_cliente"),
    path('export/xls/',export_clientes_xls, name='export_clientes_xls'),
    path('export/xlss/',export_nota_venta_xls, name='export_nota_venta_xls'),
    path('registro/',registro,name="registro"),
    path('reporte/',reporte,name="reporte"),
]

app/models.py
from django.db import models

# Pestaña models, se crean las tablas para su posterior migración (comando py manage.py makemigrations)


class Clientes(models.Model):
    id_cliente = models.IntegerField()
    rut = models.CharField(max_length=50)
    nombre_compania = models.CharField(max_length=50)
    telefono = models.IntegerField()
    email = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.nombre_compania


#estado_nv = (
#    (0,'Sin Seleccionar'),
#    (1,'Aprobado'),
#    (2,'En Progreso'),
#    (3,'Abortada'),
#    (4,'Finalizada'),
#    (5,'Eliminado'),
#)




clase_venta = [

    [0, "Contado"],
    [1, "Credito"]
]


class N_venta(models.Model):
    id_cliente = models.ForeignKey(Clientes, on_delete=models.PROTECT)
    nombre_venta = models.CharField(max_length=50)
    fecha_venta = models.DateField()
    clp = models.IntegerField()
    clase_venta = models.IntegerField(choices=clase_venta)
    fecha_inicio_facturacion = models.DateField()
    fecha_fin_facturacion = models.DateField()
    #estado_nota_venta = models.IntegerField(choices=estado_nv, default=0)
    def __str__(self):
        return self.nombre_venta

app/templates/app/adm_clientes.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Administración de Clientes</title>
{% endblock %}

{% block contenido %}

{% load crispy_forms_tags %}


<div class="row">
    
    <div class="col-12 col-md-6 offset-md-3">
        
        <div class="card">
            <div class="card-body">
                <h2 style="text-align: center;">Administración de Clientes</h2>
                
                <form action="" method="post">

                    {% csrf_token %}
                    {{ form | crispy}}
                    
                   
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
           
             </div>
         </div>    
        </form>
        

    </div>
   

{% endblock %}

app/templates/app/adm_nota_venta.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Administración de Nota de Venta</title>
{% endblock %}

{% block contenido %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2 style="text-align: center;">Administración de Notas de ventas</h2>
                <form action="" method="post">

                    {% csrf_token %}
                    {{ form | crispy}}

                    
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
           
             </div>
         </div>    
        </form>

    </div>

   


{% endblock %}

app/templates/app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="{% static 'app/img/logo.png'%}">
  <!--Modifica el titulo de la pagina en la cual se encuentre-->
  {% block tituloseccion %}

  {% endblock %}
  <!--Estilo css base -->
  <link rel="stylesheet" href="{% static 'app/css/base.css' %}">
  <!--Estilo css index -->
  <link rel="stylesheet" href="{% static 'app/css/index.css' %}">
  <!--Estilo css Registro -->
  <link rel="stylesheet" href="{% static 'app/css/registro.css' %}">
  <!--Estilo css Reporte-->
  <link rel="stylesheet" href="{% static 'app/css/reporte.css' %}">

  <!--conectar google fonts-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Benne&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@600&display=swap" rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <!--animate.css-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

  <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

  <!--Link a opciones.js-->
  <link rel="stylesheet" href="{% static 'app/js/opciones.js' %}">
</head>

<body>

  <!--SECCIÓN SUPERIOR-->
  <div class="container">
    <!--Menú Flotante-->
    <div class="row barra-nav">
      <!--Barra de Navegación-->
      <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4 col-xxl-4">
        <div id="myNav" class="overlay ">
          <a href="javascript:void(0)" class="closebtn link-menus" onclick="closeNav()">&times;</a>
          <div class="overlay-content">
            <a class="link-menus"  href=" {% url 'index' %} ">Home</a>
            <!--Permite el acceso al usuario que contega el permiso para agregar clientes-->
            {% if perms.app.add_clientes  %}
            <a class="link-menus"  href=" {% url 'adm_clientes' %} ">Administracion de Clientes</a>
            {% endif %}
            <!--Permite el acceso al usuario que contega el permiso para agregar una nota de venta-->
            {% if perms.app.add_n_venta  %}
            <a class="link-menus"  href=" {% url 'adm_ventas' %} ">Administracion de Nota de Venta</a>
            {% endif %}
            <!--Permite el acceso al usuario que contega el permiso para visualizar clientes-->
            {% if perms.app.view_clientes  %}
            <a class="link-menus"  href="{% url 'listar_clientes' %}">Listar Clientes</a>
            {% endif %}
            <!--Permite el acceso al usuario que contega el permiso para Visualizar clientes-->
            {% if perms.app.view_n_venta  %}
            <a class="link-menus"  href="{% url 'listar_ventas' %}">Listar Ventas</a>
            {% endif %}
            <!--Permiso parche-->
            {% if perms.app.delete_clientes %}
            <a class="link-menus"  href=" {% url 'registro' %} ">Administración de Usuarios</a>
            {% endif %}
            <!--Permiso parche-->
            {% if perms.app.delete_clientes %}
            <a class="link-menus"  href=" {% url 'reporte' %} ">Reporte PowerBI</a>
            {% endif %}
            <!--Autentifica a los usuarios-->
          </div>
          {% if user.is_authenticated %}
          <a class="cerrar" href=" {% url 'logout' %} ">Cerrar sesión</a>
          {% else %}
          <a class="link-menus" href=" {% url 'login' %} ">Iniciar sesión</a>
          {% endif %}
        </div>
      </div>
      <!--Imagen Parte Superior-->
      <div class="logo-titulo col-6 col-sm-6 col-md-6 col-lg-4 col-xl-4 col-xxl-4">
        <img class="logo1" src="{% static 'app/img/logo.png'%}" alt="logo1">
        <h2 class="titulo animate__animated animate__fadeInRight">SixManager Software</h2>
      </div>
      <div class="col-6 col-sm-6 col-md-6 col-lg-4 col-xl-4 col-xxl-4">
        <span class="menu " onclick="openNav()">&#9776;</span>
      </div>
    </div>
  </div>
  <!--SECCION CENTRAL-->
  {% block contenido %}

  {% endblock %}
  <!--SECCIÓN INFERIOR-->
  <!--Footer-->
  <footer class="piebg-light text-center text-lg-start" heidth=50%>
    <!-- Copyright -->
    <div class="text-center p-3" >
      © 2021 SixManager Software
    </div>
    <!-- Copyright -->
  </footer>
  <script src="{% static 'app/js/opciones.js' %}"></script>
  <script src="{% static 'app/js/jquery-3.6.0.min.js' %}"></script>
  <script src="{% static 'app/js/bootstrap.min.js' %}"></script>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>


  {% if messages %}
  {% for m in messages %}
  <script>
    Swal.fire({
      "title": "{{m}}",
      "icon": "success"
    })
  </script>
  {% endfor %}
  {% endif %}

</body>

</html>

app/templates/app/index.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Home</title>
{% endblock %}

{% block contenido %}
<div class="container">
  
    <div class="card-body">
      <div class="row ">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
          <h2 class="titulo-index animate__animated animate__fadeInDown" >Sistema de Gestión Web</h2>
          <hr>
          {% if user.is_authenticated %}
          <h5 class="subtitulo-index animate__animated animate__fadeInDown">Bienvenido {{ user.username }} </h3>
          {% endif %}
          <br>
          <p class="descripcion-index animate__animated animate__fadeInDown">Este sistema
            tiene como función administrar las ventas emitidas por nuestra empresa y los
            clientes con los cuales se trabajan. La plataforma esta orientada para que nuestros
            vendedores o gerentes puedan ejercer de manera eficiente las funciones requeridas para su cargo.
          </p>
          <br>
          <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
            <img class="imagen-index animate__animated animate__fadeInLeft" src="{% static 'app/img/teclado.png'%}" alt="Imagen index">
          </div>
          <br>
          <br>
          <hr>
          <br>
        </div>
      </div>
    </div>
  
</div>
{% endblock %}

app/templates/app/listar_clientes.html
{% extends 'app/base.html' %}



{% load static %}



{% block tituloseccion %}
<title>SixManager | Listado de Clientes</title>
{% endblock %}


{% block contenido %}
{% load humanize %}

{% block js %}
<script>
    function eliminarCliente(id) {
        Swal.fire({
            "title": "¿Estás seguro?",
            "text": "Esta acción no se puede deshacer",
            "icon": "warning",
            "showCancelButton": true,
            "cancelButtonText": "No, cancelar",
            "confirmButtonText": "Si, Eliminar",
            "reverseButtons": true,
            "confirmButtonColor": "#dc3545",

        })
            .then(function (result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar_cliente/" + id
                }
            })
    }
</script>
{% endblock %}

<br>
<br>
<div class="card">
    <div class="card-body text-center">
        <h2 style="text-align: center;">Clientes ingresados</h2>
        <a href="{% url 'export_clientes_xls' %}" class="btn btn-success btn-sm">Exportar a excel</a>
        <hr>
        <form method="GET">
            {{myfilter.form}}
            <button class="btn btn-outline-info btn-sm" type="submit">Buscar</button>
        </form>
        
        
      </form>
        <hr>
        <table class="table table-hover">
            <tr>

                <th>ID Cliente</th>
                <th>Rut</th>
                <th>Nombre compañia</th>
                <th>Telefono</th>
                <th>Email</th>
                <th>Dirección</th>
                <th>Opciones</th>
                

            </tr>

            {% for p in clientes %}

            <tr>
                <td>{{ p.id_cliente | title }}</td>
                <td>{{ p.rut | title }}</td>
                <td>{{ p.nombre_compania | title }}</td>
                <td>{{ p.telefono | title }}</td>
                <td>{{ p.email | title }}</td>
                <td>{{ p.direccion | title }}</td>
                <td>
                    <!--Permite el acceso al boton, dependiendo de los permisos del usuario(modificar cliente)-->
                    {% if perms.app.change_clientes %}
                    <a href="{% url 'modificar_clientes' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                    {% endif %}
                    <!--Permite el acceso al boton, dependiendo de los permisos del usuario(eliminar cliente)-->
                    {% if perms.app.delete_clientes %}
                    <!-- <a href="#" onclick="eliminarCliente({{ p.id }})" class="btn btn-danger btn-sm">Eliminar</a> -->
                    {% endif %}
                </td>
            </tr>

            {% endfor %}
        </table>
        <hr>
    </div>
</div>


{% endblock %}

app/templates/app/listar_ventas.html
{% extends 'app/base.html' %}

{% load static %}




{% block tituloseccion %}
<title>SixManager | Listado de Nota de Venta</title>
{% endblock %}



{% block contenido %}
{% load humanize %}

{% block js %}
<script>
    function eliminarVenta(id) {
        Swal.fire({
            "title": "Estás seguro?",
            "text": "Esta acción no se puede deshacer",
            "icon": "warning",
            "showCancelButton": true,
            "cancelButtonText": "No, cancelar",
            "confirmButtonText": "Si, Eliminar",
            "reverseButtons": true,
            "confirmButtonColor": "#dc3545",

        })
            .then(function (result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar_venta/" + id
                }
            })
    }
</script>

{% endblock %}

<br>
<br>
<div class="card">
    <div class="card-body text-center">
        <h2 style="text-align: center;">Notas de venta ingresadas</h2>
        <a href="{% url 'export_nota_venta_xls' %}" class="btn btn-success btn-sm">Exportar a excel</a>
        <hr>
        <form method="GET">
            {{myfilter1.form}}
            <button class="btn btn-outline-info btn-sm" type="submit">Buscar</button>
        </form>
        <hr>
        <table class="table table-striped table-hover">
            <tr>
                <th>Nombre Cliente</th>
                <th>Nombre Venta</th>
                <th>Fecha Venta</th>
                <th>Monto en CLP</th>
                <th>Clase de Venta</th>
                <th>Fecha inicio Facturacion</th>
                <th>Fecha Fin Facturacion</th>
                <th>Opciones</th>

            </tr>

            {% for p in ventas %}

            <tr>
                <td>{{ p.id_cliente | title }}</td>
                <td>{{ p.nombre_venta | title }}</td>
                <td>{{ p.fecha_venta | title }}</td>
                <td>${{ p.clp | title }}</td>
                <td>{{ p.clase_venta | title}}</td>
                <td>{{ p.fecha_inicio_facturacion | title }}</td>
                <td>{{ p.fecha_fin_facturacion | title }}</td>
                <td>
                    <!--Permite el acceso al boton, dependiendo de los permisos del usuario(modificar cliente)-->
                    {% if perms.app.change_n_venta %}
                    <a href="{% url 'modificar_venta' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                    {% endif %}
                    <!--Permite el acceso al boton, dependiendo de los permisos del usuario(eliminar cliente)-->
                    {% if perms.app.delete_n_venta %}
                   <!-- <a href="#" onclick="eliminarVenta({{ p.id }})" class="btn btn-danger btn-sm">Eliminar</a> -->
                    {% endif %}
                </td>
            </tr>

            {% endfor %}
        </table>
        <hr>

    </div>
</div>


{% endblock %}

app/templates/app/loginopcion.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SixManager | Selección Usuario</title>
    {% load static %}
    <link rel="shortcut icon" href="{% static 'app/img/logo.png'%}">
    <!--conectar google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--animate.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

    <link rel="stylesheet" href="{% static 'app/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'app/css/login.css' %}">
    <link rel="stylesheet" href="{% static 'app/css/loginopcion.css' %}">

</head>

<body>
    <div class="container">
        <div class="row">
            <div class=" col-12 col-md-6 offset-md-3">
                <div class="sombra card">
                    <div class="card-body">
                        <img class="logo-option-login" src="{% static 'app/img/image.png'%}" alt="logo-login">
                        <br>
                        <h2 class="titulo-login-opt">Selecciona tu tipo de usuario</h2>
                        <br>
                        <hr>
                        <div class="row">
                            <div class="cont-boton col-12  col-md-12 col-lg-12">
                                <!--Redirecciona a la url del admin-->
                                <a class="boton-select  btn btn-primary" href="{% url 'admin:index' %} " role="button">Administrador</a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="cont-boton col-12 col-md-12 col-lg-12">
                                <!--Redirecciona a la url del login-->
                                <a class="boton-select btn btn-primary" href="{% url 'login' %} " role="button">Vendedor/Gerente</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/app/modificar_clientes.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Modificador de Clientes</title>
{% endblock %}


{% block contenido %}

{% load crispy_forms_tags %}


        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                        <h2>Modificar Clientes</h2>
                        <form action="" method="post">

                            {% csrf_token %}
                            {{ form | crispy}}
                            
                            <div class="d-flex justify-content-end">
                                <input type="reset" value="Cancelar" class="btn btn-secondary">
                                &nbsp;
                                <input type="submit" value="Modificar" class="btn btn-primary">
                            </div>
                   
                     </div>
                 </div>    
                </form>
            

            </div>
        </div>

 

{% endblock %}

app/templates/app/modificar_venta.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Modificador de Nota de Venta</title>
{% endblock %}



{% block contenido %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Modificar Notas de ventas</h2>
                <form action="" method="post">

                    {% csrf_token %}
                    {{ form | crispy}}
                    
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Modificar" class="btn btn-primary">
                    </div>
           
             </div>
         </div>    
        </form>

    </div>


{% endblock %}

app/templates/app/reporte.html
{% extends 'app/base.html' %}

{% load static %}

{% block tituloseccion %}
<title>SixManager | Home</title>
{% endblock %}

{% block contenido %}
<div class="container">
  <div class="sombra card">
    <div class="card-body">
        <div class="row ">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12">
              <h1 class="titulo-reporte">Reportes SixManager</h1>
              <hr>
            </div>
      <div class="row ">
        <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 col-xxl-12 imag-reporte">
          <iframe width="1140" height="541.25" src="https://app.powerbi.com/reportEmbed?reportId=a8067519-63d1-46fb-a812-704ec659221b&autoAuth=true&ctid=72fd0b5a-8a6a-4cff-89f6-bde961f7e250&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly93YWJpLXNvdXRoLWNlbnRyYWwtdXMtcmVkaXJlY3QuYW5hbHlzaXMud2luZG93cy5uZXQvIn0%3D" frameborder="0" allowFullScreen="true"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}